# Generated by Django 6.0.1 on 2026-01-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=20)),
                ('item_description', models.CharField(max_length=100)),
                ('item_price', models.FloatField()),
                ('available_stock', models.IntegerField()),
            ],
        ),
    ]
